name: Check style

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}

jobs:
  check-style:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Prepare Linux
      run: |
        sudo apt-get update -y
        sudo apt-get install jq -y

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: /home/runner/style-tools
        key: style-${{ hashFiles('.github/style-tools.sha256') }}

    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        mkdir -p /home/runner/style-tools
        cp .github/style-tools.sha256 /home/runner/style-tools
        cd /home/runner/style-tools
        wget -O clang-format https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-796e77c/clang-format-20_linux-amd64
        sha256sum -c style-tools.sha256
        chmod +x clang-format

    - name: Check code style (ClangFormat)
      run: |
        export PATH=/home/runner/style-tools:$PATH
        clang-format -version
        scripts/fix_style.py --dry-run

    - name: Check header guards
      run: scripts/check_header_guards.py

    - name: Check unused header files
      run: scripts/check_unused_header_files.py

    - name: Lint JSON
      run: |
        while read -r json;
        do
          jq '.' "$json" || { echo "$json"; exit 1; };
        done < <(find . -name "*.json");
